### ISSUE TITLE
SEHException loading torchscript model

### ISSUE THREAD

**Issue by snakex64** [dotnet/TorchSharp#1003]
Hi! I exported a torchscript model with detectron2 in their Colab tutorial file using the following command :

```
./detectron2/tools/deploy/export_model.py --config-file detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml \
    --output ./output --export-method tracing --format torchscript \
    MODEL.WEIGHTS output/model_final.pth \
    MODEL.DEVICE cuda
```

I then tried to load it with TorchSharp :
`var m = torch.jit.load(@"model.ts");`

Unfortunately I get the following exception : `System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'`

Any way to diagnose this ? I am using TorchSharp-cpu version 0.100.0

Thanks,

**Comment by NiklasGustafsson** [comment]
Does the problem look anything like the one in this issue:

https://github.com/dotnet/TorchSharp/issues/999

**Comment by snakex64** [comment]
> Does the problem look anything like the one in this issue:
> 
> #999

For me it works using 0.99.6. I can load the model in python if I have torchvision imported too. I added the torchvision nuget package too in my app but it has the same crash. Would love to have a way to get the actual error, it would help a lot.

**Comment by NiklasGustafsson** [comment]
I wonder if the root cause is the same as in that other issue. If you scroll down quite a bit on that one, you'll see that someone who was running into the issue worked around it by (manually) replacing the CUDA 11.7 binaries that TorchSharp bundles with the CUDA 11.8 libtorch binaries in the bin directory (after building). 

It's worth a try, and if that addresses the issue for you, then that's more information for us to work with on the problem.

**Comment by NiklasGustafsson** [comment]
BTW, what version of the NVIDIA driver are you using? That is one thing we've seen different between the machines I'm testing on, which don't have the #999 issue, and those who are reporting the error -- I'm on an older driver.

**Comment by snakex64** [comment]
I tried to download tons of TorchSharp zip, release and debug, with the same behavior with them all. The sad thing is that the error is so generic that maybe it helped and fixed something but there was another error after and I can't know it.

Not sure for the driver, I have a quadro T2000 and in the device manager I can see "Driver Version 31.0.15.1766".

I have also tried with the TorchSharp-cpu package and it gives a SEHException too

**Comment by NiklasGustafsson** [comment]
Ahh, if it fails on CPU, then it's definitely different from #999 -- that's a CUDA version problem of some sort.

If you have the TorchScript model and some console app that loads it and runs into the error, you could maybe upload it somewhere that I can get to it. That way, I can try it with a debug build and maybe see if I can get more information out of it.

**Comment by snakex64** [comment]
Of course, here's the model :
https://drive.google.com/file/d/1Bg9tqi1dwoOl2DCB58UlVpSxExxsjVs6/view?usp=sharing

I started it with detectron2 based on COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x

As for the program, I only have 1 line ahah : `torch.jit.load("model.ts")`
I have both TorchSharp-cpu and TorchVision 0.100.0, and also tried TorchSharp-cuda-windows.

I have been trying to compile a test project in C++ with libtorch and torchvision for 2 days now without success. I managed to have libtorch working pretty easily but torchvision is about to make me break my screen 😒. I wanted to see if it was at least loading directly using their lib but I can't make it work, there's always an issue somewhere along the way 😆

**Comment by NiklasGustafsson** [comment]
Well, I can confirm that I'm seeing the same exception -- it's crashing somewhere in the middle of NTDLL and doesn't give any kind of useful stack trace (unlike what a C++ exception would have).

When I load this in Python without first importing torchvision, it complains about not having `nms` available to it. That's a native-implemented torchvision operator, and one that is on the backlog for TorchSharp to implement. Since this is TorchScript-based and operators will be loaded with TorchScript instead of TorcSharp, you may get away with some hacking / trickery:

Assuming you are on Windows, if you have installed torchvision via 'conda' as I have, then in `Miniconda3\Lib\site-packages\torchvision`, you should find:

```
_image.pyd
_C.pyd
```

If you installed via pip, I'm not sure where the binaries would be.

Copy them to the bin folder of your C# application and replace the `.pyd` extensions with `.dll`. Let me know what the outcome is. Make sure that torchvision being a CPU or CUDA build corresponds to the TorchSharp backend you've taken a dependency on (libtorch-cpu or libtorch-cuda-windows).

**Comment by NiklasGustafsson** [comment]
>> I have been trying to compile a test project in C++ with libtorch and torchvision for 2 days now without success.

Where did you find the TV native binaries?

**Comment by NiklasGustafsson** [comment]
It's odd that it works with 0.99.6...

**Comment by snakex64** [comment]
> It's odd that it works with 0.99.6... Maybe it's worth trying the 11.8 replacement workaround: [#999 (comment)](https://github.com/dotnet/TorchSharp/issues/999#issuecomment-1561554522)

It doesn't work in 0.99.6 either (unless you managed to make it work, my tests weren't successful)

> Copy them to the bin folder of your C# application and replace the `.pyd` extensions with `.dll`. Let me know what the outcome is. Make sure that torchvision is a CPU or CUDA build that corresponds to the TorchSharp backend you've taken a dependency on (libtorch-cpu or libtorch-cuda-windows).
> 
> You may also need to copy these dlls:
> 
> ```
> libjpeg.dll
> libpng16.dll
> nvjpeg64_11.dll
> ```

I tried what you suggested with the .dll, I have : 
`torchvision-0.16.0a0+4125d3a-py3.11-win-amd64` with `TorchSharp-cuda-windows`, took the 2 pyd files renamed with .dll + the 3 .dll mentionned, I still get the same SEHException. I didn't have a `_image.pyd` file though, I had a `image.pyd`, I assumed it was that one.

> > > I have been trying to compile a test project in C++ with libtorch and torchvision for 2 days now without success.
> 
> Where did you find the TV native binaries?

At this point I'm just trying to make it work whether it's in C# or in C++. I didn't find any prebuilt binaries + .lib files I could use to make a C++ program, I was trying to build the library from source. I tried following a couple tutorial online and tried the official "doc" here : [https://github.com/pytorch/vision#using-the-models-on-c](https://github.com/pytorch/vision#using-the-models-on-c). I just went from errors to problems to other errors for way too many hours before I gave up ahah.

**Comment by NiklasGustafsson** [comment]
> It doesn't work in 0.99.6 either (unless you managed to make it work, my tests weren't successful)

Oh? You said earlier that it did work on 0.99.6.

Anyway, it was worth a try. I do believe that the issue is that the native kernel for `nms` isn't available in TorchSharp, so we're not distributing the right. It's on the backlog, but it's quite a complex implementation. I was hoping to be able to just piggy-back on the TV distribution, but that requires a bit of finagling (essentially, automating the process I described above).

**Comment by snakex64** [comment]
Damn, went back to read and I did say that, but that's just dumb me miswriting, that's why I followed up with "I added the torchvision nuget package too in my app but it has the same crash"

Is there any way I could get the actual error ? ex in libtorch in c++ I could do "e.what()" and I saw it was complaining about nms, would love to be able to have the same here.

Did you manage to make the model work with the "piggy-back" way you are mentioning ? To be sure that i'm not the one messing up something in the manipulation or my setup. I don't mind at all having to do that for now specially knowing it should work by itself at some point when it is properly supported.

I appreciate your help a lot 😊

**Comment by NiklasGustafsson** [comment]
No, after convincing myself that I had the right config alignment (CUDA vs CPU), I made the copies and it still didn't work.

I don't know how to get more info out of an SEHException -- it's such a low-level construct, and you don't see them very often. It's like seeing a SIGSEGV on Linux -- something fundamental is wrong.

I've been thinking about implementing `nms` in C# -- it would be portable between CPU and CUDA, but maybe not as performant. That said, that wouldn't help with TorchScript, since it won't find the native implementation it's looking for.

Maybe that's it -- it's not enough for it to find the DLLs, it needs to see a registration of the operator, too. Here's what Python says when I haven't imported torchvision:

```
>>> torch.jit.load("d:\\downloads\\model.ts")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Miniconda3\lib\site-packages\torch\jit\_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError:
Unknown builtin op: torchvision::nms.
Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
```

**Comment by NiklasGustafsson** [comment]
Okay, so egg on my face -- -there's already a managed-code implementation of `nms` in the TorchVision package. Won't help with TorchScript...

**Comment by NiklasGustafsson** [comment]
### __HACK ALERT__

Here's what worked for me (just loaded the module, didn't try sending data through it) after copying the DLLs to the bin folder:

```C#
[DllImport("_C")] internal static extern IntPtr PyInit__C();

[...]

PyInit__C();

var m = torch.jit.load<Tensor, Tensor>(@"d:\Downloads\model.ts");
```

**Comment by snakex64** [comment]
Damn, you are a life saver 🙌. I will check on my work computer tomorrow, I don't have all the info here. I tried to export to ONNX before torchscript and ONNX was giving me a input shape of [3, 800, 1202]. Which to be fair was kind of weird, and it was saying that it was "byte" types, even though the 

The next step after being able to load the model will be to figure out how to use it ahah.
Sounds like a problem for future me though from what I understand the the mask_rcnn_R_50_FPN_3x should have float as input with values between 0-1.

I'm hoping I can get more stuff out of the model using detectron2 before I export it.

Thanks a lot again, I shall try that tomorrow for sure

> ### **HACK ALERT**
(I nearly just skipped the notification on my phone when I saw HACK ALERT in big 😆)

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson 
This is an interesting Hack Alert!
Hope some day will be part of FAQ :-)

**Comment by NiklasGustafsson** [comment]
> Hope some day will be part of FAQ :-)

I hope some day it won't be necessary. :-)

**Comment by NiklasGustafsson** [comment]
BTW, @snakex64 -- the reason you had trouble with TV in C++ is probably because the Windows binaries are a release build. One of the things that complicate using C++ on Windows is that you have to have different binaries for DEBUG and NDEBUG, and you can't mix and match. After getting your TorchScript module to work, I tried to build the C# TorchVision library against the _C.dll, and it blows up in the Debug build, but works correctly (including on CUDA) in a Release build. There are two C/C++ downloads for libtorch on Windows, but just a release build for torchvision.

Debug builds of TorchSharp is something that only concerns those of us who build TorchSharp from source.

**Comment by NiklasGustafsson** [comment]
BTW, I have not been able to play the same trickery on Linux -- copying the .so file is not enough. I suspect that it has something to do with dependencies also having to be moved over, but I'm not sure how to examine the dependencies of a .so file.

**Comment by snakex64** [comment]
Damn, that's good to know. We were hoping to use that on jetson boards. I guess we won't be able to 🥲

**Comment by snakex64** [comment]
Thanks a lot @NiklasGustafsson .
I managed to make it work with the model too. Turns out I needed to save the model config/yml file and re-use it after the training when exporting to torchscript. 
It works well on GPU too!
