### ISSUE TITLE
LibTorch Data Loader in TorchSharp

### ISSUE THREAD

**Issue by artidoro** [dotnet/TorchSharp#101]
We have not yet added bindings for the LibTorch data loader.

In the end-to-end examples the hardest part was actually to create the specific loader for the dataset used. The current approach is not easily scalable since it requires that for each dataset we write a loader in C++ and add a binding in C#. We need instead to create bindings to the general purpose loader in LibTorch so that users can load any dataset and specify the format directly from the C# side.

I think this is high priority issue but I am afraid it will not be very easy!

@interesaaat since you have already written two loaders, is there any API description for how the loader works in C++?

**Comment by interesaaat** [comment]
Not really. I simply looked at the loaders implementation either in [Python](https://github.com/pytorch/vision/blob/master/torchvision/datasets/cifar.py) or in [C++](https://github.com/pytorch/examples/blob/master/cpp/mnist/mnist.cpp). The problem is the transformations that you need to do on the data once you load it. I think that our best bet is to use ML.NET for this, instead of having to implement our own loader for each dataset.

**Comment by markusweimer** [comment]
> I think that our best bet is to use ML.NET for this, instead of having to implement our own loader for each dataset.

What implications does this have on the .NET dependency of the resulting model? Does the reader become part of the model?
