### ISSUE TITLE
torch.from_array loads data slowly

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#1035]
var output = torch.from_array(result_array).reshape(8, 512, 512);// result_array float[] cost 600ms.  slowly.

**Comment by GeorgeS2019** [comment]
Provide a zip project so others can debug 
Please read other issues to see how this is typically handled

**Comment by williamlzw** [comment]
torchsharp 0.100.3


using TorchSharp;

class Program
{
    static void Main(string[] args)
    {
        int size = 512;
        var bytesall = new float[size *size * 6];
        var timeCopyDataStart = DateTime.Now;
        var tensorall = torch.from_array(bytesall).reshape(size, size, 6);
        var timeCopyDataEnd = DateTime.Now;
        Console.WriteLine($"cost:{(timeCopyDataEnd - timeCopyDataStart).TotalMilliseconds}");
        Console.ReadLine();
    }
}

**Comment by NiklasGustafsson** [comment]
@williamlzw what is the timing if you take out the call to `reshape`? I expect that it is not having much of an impact, but it is a difference between the Numpy and the TorchSharp versions.

Also, to make a fair comparison, in my opinion, you would need to first make the call (to each library) that isn't timed, so that you get past the startup costs of loading the .NET code, compiling it, etc. In other words, you should compare after warm-up and see what that does to the timings.

**Comment by GeorgeS2019** [comment]
@williamlzw 

To understand how to substitute NumpyDotNET codes with Torchsharp, Study the pytorch and TorchSharp example here

- [PyTorch](https://jamesmccaffrey.wordpress.com/2023/06/09/using-pytorch-to-generate-synthetic-data-for-a-regression-problem/)
- [TorchSharp](https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/CSharp/synthetic_data.ipynb)

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- there's nothing wrong with the code itself, it's just that the `reshape` call adds some (probably very little) overhead, and not warming up the runtime will also add overhead, which I believe is being measured in the timings.

**Comment by williamlzw** [comment]
My code uses the onnxruntime to reason, which used torchsharp for post-processing but now uses numpydotnet for post-processing. I close this issue.
