### ISSUE TITLE
torchsharp tensor load and save incompatible with pytorch

### ISSUE THREAD

**Issue by BalashovK** [dotnet/TorchSharp#1101]
c# tensor.Save and Load, and also torch.Save and .Load seems to  be closer to python torch.jit.Save and Load.
.pt file from c# contains subfolder "code" and constraints.pkl
It makes it incompatible with python implementation.
python tensor.save and torch.save saves .pt file with just subfolder data, files data.pkl and version

while it is possible to load a tensor saved from C# into python with torch.jit.load, it got loaded in wrapped format and needs to be unwrapped. It is not clear how to pass a tensor back from python into c#.

That limits usability of torchsharp for more advanced use-cases.

Can you please make torchsharp tensor load and save compatible with pytorch?

**Comment by BalashovK** [comment]
Technically, when pytorch saves a tensor, it saves "torch._utils_rebuild_tensor_v2"
when torchsharp saves a tensor, it saves __torch__Module with torch._utils_rebuild_tensor_v2 inside

You can see it in data.pkl which is inside of .pt file

**Comment by NiklasGustafsson** [comment]
Generally speaking, Pytorch relies on pickling, which .NET does not support -- it is a very capable Python-specific serialization format with no perfect-fidelity implementation in .NET. There are native APIs to save modules, but the realization on load is not useful. In fact, we might remove those interfaces from TorchSharp, since they're not very functional.

In order to address this, we invented a specific format for saving weights only, which you can use to transfer state-dicts between PyTorch and TorchSharp. This format requires that you translate the model from Python to .NET with very high fidelity (fields have to be called the same, etc.). The other way to transfer models is to use TorchScript.

See: 
https://github.com/dotnet/TorchSharp/wiki/Sharing-Model-Data-between-PyTorch-and-TorchSharp
https://github.com/dotnet/TorchSharp/wiki/TorchScript

**Comment by NiklasGustafsson** [comment]
@BalashovK -- have your questions been answered here?

**Comment by BalashovK** [comment]
Yes, thank you!
