### ISSUE TITLE
System.DllNotFoundException:“Unable to load DLL \xx\xx\LibTorchSharp.dll' or one of its dependencies: 找不到指定的程序。 (0x8007007F)”

### ISSUE THREAD

**Issue by Nagisakurumi** [dotnet/TorchSharp#364]
.net 5.0

All code :

            Module module = Module.Load(@"rect.pt");
            module.cuda();

nuget download   TorchSharp   and    libtorch-cuda-10.2-win-x64
I have installed cuda 10.2 and pytorch - py3.7 on my pc.
I‘m sure model - rect.pth It runs normally on python 
I convert rect.pth to rect.pt ,then it runs error on .net

**Comment by pkese** [comment]
I don't think Python generated `.pt` files can be loaded into TorchSharp quite yet.

See https://github.com/dotnet/TorchSharp/discussions/335 and https://github.com/dotnet/TorchSharp/issues/146

`Module.Load` in TorchSharp is currently using a proprietary format, that is different from PyTorch's .pt.
It works fine for saving and loading TorchSharp model parameters, though.

**Comment by Nagisakurumi** [comment]
> I don't think Python generated `.pt` files can be loaded into TorchSharp quite yet.
> 
> See #335 and #146
> 
> `Module.Load` in TorchSharp is currently using a proprietary format, that is different from PyTorch's .pt.
> It works fine for saving and loading TorchSharp model parameters, though.

I retry model.pth then it still have an error  "System.DllNotFoundException:“Unable to load DLL 'LibTorchSharp' or one of its dependencies: "
code : 
Module module = Module.Load(@"model.pth");
            module.cuda();

**Comment by dsyme** [comment]
You'll also need the libtorch-cuda-11.1 packages

**Comment by NiklasGustafsson** [comment]
I'm pretty sure the DLL not found exception is unrelated to model loading. 

On the former, Don Syme is right, you also need to install one of the native LibTorch packages -- since you may or may not have a GPU, TorchSharp requires you to install the native package that corresponds to your configuration (CPU or GPU).

On the latter: PyTorch relies on a Python specific serialization format, "pickling," which .NET does not support well. Therefore, if you want to load model weights from PyTorch into TorchSharp, you have to export the models using a special format. This is also the format that TorchSharp uses for its own needs. See a longer explanation here: https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md

**Comment by NiklasGustafsson** [comment]
Stale.
