### ISSUE TITLE
How to create a tensor using List<int[]>

### ISSUE THREAD

**Issue by aiqinxuancai** [dotnet/TorchSharp#469]
I've been trying to translate python scripts to learn the torch framework, and I always feel like I'm missing something in torchsharp, or maybe I'm missing it.
python：
![image](https://user-images.githubusercontent.com/4475018/144020458-f3b84b88-c3c6-45e0-9b9d-066678ab0a15.png)

How to create a tensor using List<int[]> or int[,]?
![image](https://user-images.githubusercontent.com/4475018/144020895-b1703cf3-0efc-4dab-8525-40fe4334bcb6.png)

**Comment by NiklasGustafsson** [comment]
@aiqinxuancai -- a question like this is probably best surfaces as a discussion topic rather than an issue.

You can create a tensor from a list of any element type. There's currently no support for lists of lists List<int[]>, or multi-dimensional arrays int[,]. Use LINQ to transform the former into a list of integers.

```C#
public static Tensor tensor(IList<int> rawArray, long[] dimensions, torch.ScalarType? dtype = null, torch.Device device = null, bool requiresGrad = false)
```

**Comment by aiqinxuancai** [comment]
Sorry, next time will pay attention to this type posted to the discussion.
The problem has been solved, thank you for your help.
![image](https://user-images.githubusercontent.com/4475018/144162079-2b7247a3-dd17-4fa2-97ed-42a32e99026e.png)
