### ISSUE TITLE
How to load saved model in Python?

### ISSUE THREAD

**Issue by Leo-LiHao** [dotnet/TorchSharp#551]
Hi, I saved a model in C# like this:
https://github.com/dotnet/TorchSharp/blob/664dbda4cf405f6d59cc06e157359896e8a8a217/src/Examples/MNIST.cs#L99

I tried to load the saved state_dict in Python via `torch.load` but failed:

```
_pickle.UnpicklingError: pickle data was truncated
```

Is there a way to load the saved `state_dict` in Python? Thank you!

**Comment by pkese** [comment]
Did you check [model.load_state_dict](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict)?

Also read https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md

**Comment by Leo-LiHao** [comment]
> Did you check [model.load_state_dict](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict)?
> 
> Also read https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md

Thank you for your reply. I checked these links but did not find the answer.

For using `model.load_state_dict`, I have to load the saved `state_dict` (which is generated by C#) first. However, I don't know how to load it in Python, `torch.load` doesn't work.

The second link is very useful if I want to save a `state_dict` in Python and load in C#. In my case, I have to save a model by C# and load it back in Python.

**Comment by NiklasGustafsson** [comment]
@Leo-LiHao , @pkese -- currently, only PyTorch -> TorchSharp is supported. The problem is that the format is the same as .NET serialization, which has some unique aspects in how strings are encoded, so it does not match the Python pickling format at all.

It should be relatively straightforward to add an 'import.py' module patterned on the 'export.py' that already exists. Sounds like a great PR waiting to happen. :-)

**Comment by Leo-LiHao** [comment]
> @Leo-LiHao , @pkese -- currently, only PyTorch -> TorchSharp is supported. The problem is that the format is the same as .NET serialization, which has some unique aspects in how strings are encoded, so it does not match the Python pickling format at all.
> 
> It should be relatively straightforward to add an 'import.py' module patterned on the 'export.py' that already exists. Sounds like a great PR waiting to happen. :-)

Thank you! I submitted a PR which works in my use case.

**Comment by GeorgeS2019** [comment]
@NiklasGustafsson  Not sure if [this is relevant: [How I can deserialize python pickles in C#?](https://stackoverflow.com/questions/14922722/how-i-can-deserialize-python-pickles-in-c)

**Comment by NiklasGustafsson** [comment]
> @NiklasGustafsson Not sure if [this is relevant: [How I can deserialize python pickles in C#?](https://stackoverflow.com/questions/14922722/how-i-can-deserialize-python-pickles-in-c)
> 
> [Razorvine.Pickle](https://www.nuget.org/packages/Razorvine.Pick

@GeorgeS2019: not really. Relying on Python pickling would be an expensive way of accomplishing what you can do with simple means using the current approach and would mean taking a dependency on an external package that I would like to avoid. Since all you have to be able to do is serialize and deserialize string-keyed dictionaries of tensors, pickling is overkill.

The current custom approach requires that you instrument your Python code with a line or two of custom code, but it does handle the scenario.
