### ISSUE TITLE
str documentation appears to be incorrect

### ISSUE THREAD

**Issue by collinkruger** [dotnet/TorchSharp#628]
Hi 👋

https://github.com/dotnet/TorchSharp/blob/4496f5c9711ee1010c1196e13d10e9f4e7603974/src/TorchSharp/Tensor/TensorExtensionMethods.cs#L48-L52

Reading the above comment, it appears (to me) that we should be able to use `str` with a format supplied without having to supply a `style` argument. More specifically, use it as described in this tutorial. https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/CSharp/tutorial2.ipynb

It appears this no longer works.
![image](https://user-images.githubusercontent.com/23742214/174008788-f1439f11-2dfe-49f3-b671-eb447fd3f9ee.png)

I've also opened an issue in the TorchSharpExamples repo.
https://github.com/dotnet/TorchSharpExamples/issues/25

**Comment by dayo05** [comment]
TorchSharp supports various kind of style to convert tensor to string. There are torch.TensorStringStyle enum to detect the style like julia style, numpy style, etc. after version 0.96.4.
There are PR to add juliastr(), npstr() and I think this will solve the issue. #630

**Comment by NiklasGustafsson** [comment]
I took care of the problem in the TorchSharpExamples repo, adding the parameter name. We can fix it here, too, by going back and moving the new style parameter last in the argument list, but that will introduce another breaking change. Open to suggestions on what the right thing to do is. We're still < v1.0, so we can still do what's right rather than what's convenient; maybe the style argument doesn't really belong at the beginning of the list?

**Comment by NiklasGustafsson** [comment]
I will push this to 0.96.8.
