### ISSUE TITLE
Ease of use: module factories should have `dtype` and `device`

### ISSUE THREAD

**Issue by lostmsu** [dotnet/TorchSharp#743]
In PyTorch you can create modules directly on the target device, which is convenient and slightly more performant because there's no need to create buffers on CPU and move them to the target device.

**Comment by NiklasGustafsson** [comment]
This is a good idea, I think. It will require a good amount of rework -- right now, we're relying on the C++ native module implementations for a number of modules. What PT does, instead, is to wrap the functional interfaces and allocate the parameters from the Python code, which is how come PT can create them on the GPU right away.

We can split the work up into the convenience and performance aspects, so that the factories to the type and device movements first, and then add the rework of the logic that improves the performance (slightly) during model construction, separately.

**Comment by lostmsu** [comment]
Simply reimplementing in C# would make sense for the most common modules with large parameters. E.g. `Linear`.

**Comment by NiklasGustafsson** [comment]
Yes. The current implementation predated the introduction of DisposeScope, which simplified doing things in C#. I've stayed away from fixing things that aren't broken, but I can certainly do the convenience part first, and then gradually move to a C# re-implementation.

**Comment by lostmsu** [comment]
Yes, but also note `Linear` is actually pretty trivial.

**Comment by NiklasGustafsson** [comment]
That's right, but you have to make sure to get the backprop right, which is a lot harder for things like LSTM. Doing things like convolution efficiently is complicated -- a naive implementation is not efficient.
