### ISSUE TITLE
How to deal with tracing and scripting?

### ISSUE THREAD

**Issue by xhuan8** [dotnet/TorchSharp#791]
In PyTorch some code may refer to tracing and scripting, how is in TorchSharp?

```
if torchvision._is_tracing():
               return _onnx_expand_boxes(boxes, scale)

if torch.jit.is_scripting():
     if not this._has_warned:
             warnings.warn("RCNN always returns a (Losses, Detections) tuple in scripting")
             this._has_warned = True
             return losses, detections
     else:
            return this.eager_outputs(losses, detections);
```

**Comment by NiklasGustafsson** [comment]
@xhuan8 -- you have added a number of good posts lately. It would be great if you could introduce yourself briefly to the TorchSharp community in this thread: https://github.com/dotnet/TorchSharp/discussions/333

It's entirely voluntary, but would be appreciated.

**Comment by MovGP0** [comment]
Given that TorchSharp is a library and used in a wide range of applications with different strategies to logging and tracing, as well as working on different operating systems, there might not be a one-size-fits-all solution.

While `Microsoft.Extensions.Logging.ILogger<T>` is the standard for logging output (even when I prefer using [Serilog](https://serilog.net/) instead); tracing is a more complicated matter, since [Event Tracing for Windows](https://medium.com/@alexkhanin/getting-started-with-event-tracing-for-windows-in-c-8d866e8ab5f2) (ETW) using `System.Diagnostic.Tracing.EventSource` is—as the name implies—Windows specific. 

Newer approaches like [OpenTelemetry](https://opentelemetry.io/) might be helpful here, but are not much in use currently.

**Comment by xhuan8** [comment]
thanks, there are many hidden details.

**Comment by NiklasGustafsson** [comment]
> Given that TorchSharp is a library and used in a wide range of applications with different strategies to logging and tracing, as well as working on different operating systems, there might not be a one-size-fits-all solution.
> 
> While `Microsoft.Extensions.Logging.ILogger<T>` is the standard for logging output (even when I prefer using [Serilog](https://serilog.net/) instead); tracing is a more complicated matter, since [Event Tracing for Windows](https://medium.com/@alexkhanin/getting-started-with-event-tracing-for-windows-in-c-8d866e8ab5f2) (ETW) using `System.Diagnostic.Tracing.EventSource` is—as the name implies—Windows specific.
> 
> Newer approaches like [OpenTelemetry](https://opentelemetry.io/) might be helpful here, but are not much in use currently.

Now, I'm confused. Are you talking about telemetry tracing, Johann? The tracing that @xhuan8 was referring to is torch.JIT tracing (TorchScript).

**Comment by MovGP0** [comment]
@NicklasGustafsson you are right. I did confuse .NET tracing with torch.JIT tracing 🫣

**Comment by MovGP0** [comment]
I am thinking about providing either event handlers (old method) or `IObservable`s (new method), such that the user of the TorchSharp library can hook in whatever Logging/Tracing solution is preferred.
