### ISSUE TITLE
Add torch.package.PackageImporter(local_file).load_pickle("tts_models", "model") and model.save_wav()

### ISSUE THREAD

**Issue by mizantrop777** [dotnet/TorchSharp#805]
I need to port this code:

![2022-10-19_02-57-00](https://user-images.githubusercontent.com/30718125/196566512-c421e6a0-609a-496e-b354-dcebeaa16e6c.png)

**Comment by NiklasGustafsson** [comment]
Hello @mizantrop777,

Since PyTorch packages involve loading Python code, it is outside the scope of TorchSharp. It is a firm design principle of TorchSharp that it will provide access to the native libraries underneath PyTorch, i.e. "libtorch" but not require a Python environment in order to run. 

torch.package.PackageImporter could possibly be implemented outside of TorchSharp in some form of extension library, but dealing with pickling, which is a Pyton-specific serialization format, will have some challenges in .NET.

Regarding 'save_wav,' I've been searching for the documentation in PyTorch as well as the torchaudio documentation, but didn't find it. Could you point me at the docs?

Thanks,

Niklas

**Comment by kaiidams** [comment]
@mizantrop777 @NiklasGustafsson 
We have `TorchSharp.torchaudio.save()` interface, but it is a stub function. You need to register an IO backend by calling `TorchSharp.backend.utils.set_audio_backend(AudioBackend backend)`. 
There is a sample code to do it in https://github.com/dotnet/TorchSharp/blob/8a0880306d37b14aaf149bd46611085d12127844/src/Examples/SpeechCommands.cs#L50, but it only supports `load()`.

**Comment by kaiidams** [comment]
@mizantrop777 
If you want to port Silere TTS to train models yourself, you could convert their model from PyTorch to C#. If you have to only port inference code to C#, probably you could convert their models into TorchScript module or ONNX model and then either use TorchSharp to run TorchScript or use ONNX runtime to run ONNX model.
